version: "3"
services:
  project-db:
    image: mariadb:10.5
    container_name: project-db
    volumes:
      - "./docker/database/data:/var/lib/mysql"
      - "./docker/database/config:/etc/mysql/conf.d"
    ports:
      - "3386:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=balloon_db
      - MYSQL_USER=balloon_usr
      - MYSQL_PASSWORD=balloon_pwd
    networks:
      - project-network
    restart: unless-stopped

  project-webserver:
    image: nginx:alpine
    container_name: project-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "880:80"
      - "8843:443"
    volumes:
      - "./:/var/www"
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - project-network

  project-app:
    image: amoraresco/it-academy-application:latest
    container_name: project-app
    links:
      - project-db
      - project-redis
    ports:
      - "9000:9000"
      - "882:22"
    working_dir: /var/www
    volumes:
      - "./:/var/www"
    environment:
      - APP_URL=http://project.local
      - MAIL_HOST=project-mailhog
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=email@example.com
      - MAIL_NAME="My project"
      - MAIL_DELAY=2500
      - DB_HOST=project-db
      - DB_DATABASE=balloon_db
      - DB_USERNAME=balloon_usr
      - DB_PASSWORD=balloon_pwd
      - DB_PORT=3306
    networks:
      - project-network
    restart: unless-stopped

  project-mailhog:
    image: mailhog/mailhog
    container_name: project-mailhog
    ports:
      - "8025:8025"
      - "8125:1025"
    networks:
      - project-network

  project-redis:
    image: redis:3.0
    container_name: project-redis
    volumes:
      - "./docker/redis/cache/data:/data"
    ports:
      - "8379:6379"
    restart: unless-stopped
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
